### ISSUE TITLE
Chromecast not connecting successfully - Nexus 5X, libgcastv2_base.so, maruos 0.6.7

### ISSUE THREAD

**Issue by darekdeo** [maruos/maruos#123]
Whenever I try to cast my Nexus 5X to either Chromecast or Android TV I am getting "Casting screen to ChromecastName has ended". Happens every time, both on Chromecast and Android TV. Problem exists only with "Cast" available from statusbar dropdown menu, I am still able to use Chromecast from YouTube app without issues.

Steps to reproduce:
- installed twrp and rebooted phone then runned recovery
- installed maruos 0.6.7 from recovery and rebooted phone then back to recovery
- installed opengapps pico 20190926 from recovery and rebooted phone
- finished gapps installation on phone (signed to google account, etc)
- connected both devices to the same Wifi (also tried Wifi Direct from my TV)
- click Cast icon from statusbar dropdown menu
- dialog shows list of available Chromecast devices, select Chromecast or TV
- TV blinks (dark screen), phone is showing "Connecting" message for couple of seconds
- After couple of seconds toast with message "Casting screen to ChromecastName has ended" is presented on the phone. Android TV goes back to normal (from dark screen to showing Android TV dashboard with cards)

I've pulled logcat from Phone, looks like it is missing .so library (libgcastv2_base.so) or libraries. To me it looks like a problem with recent gapps, can someone confirm this? Anybody can suggest a fix? I could manually search over the web for needed .so files but there should be a better way? Also maybe maruos should display proper information message if something like this happens and provide instruction how to fix this? Below is cutted interesting part from logcat:

`09-26 15:46:59.595  4882  4888 I zygote64: Compiler allocated 4MB to compile void bwfl.b(java.lang.Object, bwhw)
09-26 15:47:00.161  4882  8448 I DeviceControllerEntry: CastDeviceController.Listener.onApplicationConnected: appId=674A0243, sessionId=7737e63c-53f0-415f-ad72-7014767a2d08
09-26 15:47:00.170  4882  8448 E MirroringControlChannel: [instance-1] offer string; {"udpPort":2346,"supportedStreams":[{"type":"audio_source","codecName":"aac","rtpProfile":"cast","rtpPayloadType":127,"ssrc":1,"storeTime":100,"targetDelay":100,"bitRate":128000,"sampleRate":48000,"timeBase":"1\/48000","channels":2,"rtpExtensions":["adaptive_playout_delay"],"receiverRtcpEventLog":true,"index":0,"aesKey":"*hidden*","aesIvMask":"*hidden*","errorRecoveryMode":"castv2"},{"type":"video_source","codecName":"h264","rtpProfile":"cast","rtpPayloadType":96,"ssrc":11,"storeTime":100,"targetDelay":100,"maxFrameRate":"60000\/1001","timeBase":"1\/90000","maxBitRate":6000000,"profile":"main","level":"4","resolutions":[{"height":720,"width":1280}],"rtpExtensions":["adaptive_playout_delay"],"receiverRtcpEventLog":true,"index":1,"aesKey":"*hidden*","aesIvMask":"*hidden*","errorRecoveryMode":"castv2","intraRefreshEnable":false}]}
09-26 15:47:00.204  4882  8448 W CDC|MRP|1: [MRP] Ignoring message. Namespace 'urn:x-cast:com.google.cast.media' has not been registered.
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: Unable to load native code from existing library /data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a/libjgcastservice.so
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Runtime.load0(Runtime.java:928)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.System.load(System.java:1621)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):8)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.a(Unknown Source:0)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastLogger.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):1)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.<init>(Unknown Source:0)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:22)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.217  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: Unable to load native code from existing library /data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a/libjgcastservice.so
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Runtime.load0(Runtime.java:928)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.System.load(System.java:1621)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):19)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.a(Unknown Source:0)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastLogger.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):1)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.<init>(Unknown Source:0)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:22)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.220  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: Unable to locate jgcastservice in dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCorePix/PrebuiltGmsCorePix.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a, /system/priv-app/PrebuiltGmsCorePix/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.System.loadLibrary(System.java:1657)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):23)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.a(Unknown Source:0)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastLogger.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):1)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastLogger.<init>(Unknown Source:0)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:22)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.225  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.225  4882  8448 E JGCastLogger: Unable to load JGCastService library
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: Unable to load native code from existing library /data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a/libjgcastservice.so
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Runtime.load0(Runtime.java:928)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.System.load(System.java:1621)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):8)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.a(Unknown Source:0)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastService.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):4)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.<init>(Unknown Source:0)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:8)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.230  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: Unable to load native code from existing library /data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a/libjgcastservice.so
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Runtime.load0(Runtime.java:928)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.System.load(System.java:1621)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):19)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.a(Unknown Source:0)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastService.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):4)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.<init>(Unknown Source:0)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:8)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.232  4882  8448 W GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: Unable to locate jgcastservice in dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/com.android.media.remotedisplay.jar", zip file "/system/framework/com.android.location.provider.jar", zip file "/system/priv-app/PrebuiltGmsCorePix/PrebuiltGmsCorePix.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_extracted_libs/arm64-v8a, /system/priv-app/PrebuiltGmsCorePix/lib/arm64, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]]
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgcastv2_base.so" not found
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.System.loadLibrary(System.java:1657)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at ssa.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):23)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at ssw.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):5)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.a(Unknown Source:0)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.cast.JGCastService.<init>(:com.google.android.gms@19275028@19.2.75 (090400-269183835):4)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at com.google.android.gms.cast_mirroring.JGCastService.<init>(Unknown Source:0)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at pvh.run(Unknown Source:8)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at sow.b(:com.google.android.gms@19275028@19.2.75 (090400-269183835):33)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at sow.run(:com.google.android.gms@19275028@19.2.75 (090400-269183835):18)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at sum.run(Unknown Source:7)
09-26 15:47:00.235  4882  8448 E GmsNativeLibraryLoader: 	at java.lang.Thread.run(Thread.java:764)
09-26 15:47:00.235  4882  8448 E JGCastService: Unable to load JGCastService library
09-26 15:47:00.235  4882  8448 W CastRouteController: [instance-1] createSourceOrSink, flags = 0x80000000
09-26 15:47:01.234  3595  4270 D WificondControl: Scan result ready event
09-26 15:47:05.468  3595  6098 E LightsService: Light requested not available on this device. 2
09-26 15:47:09.765  3595  3781 I nanohub : osLog: [AR_CHRE] still: 71
09-26 15:47:14.328  3595  3781 I nanohub : osLog: [AR_CHRE] still: 100
09-26 15:47:15.024  3595  3792 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.drive.ApiService.RESET_AFTER_BOOT flg=0x4 cmp=com.google.android.gms/.drive.api.ApiService (has extras) } U=0: not found
09-26 15:47:15.281  4882  8450 I DeviceControllerEntry: onApplicationDisconnected: castStatusCode=APPLICATION_NOT_RUNNING, sessionId=7737e63c-53f0-415f-ad72-7014767a2d08
09-26 15:47:15.294  4882  8450 I CastRouteController: [instance-1] onSessionEnded: sessionId=7737e63c-53f0-415f-ad72-7014767a2d08, castStatusCode=APPLICATION_NOT_RUNNING
09-26 15:47:15.295  4882  8450 I CastMirroringProvider: onDeviceStoppedMirroring: device="KDL-43W808C" (bc8ffa28b17d8ad831d7421c50eb2ff4), error=true
09-26 15:47:15.297  3595  3595 I MediaRouterService: Selected route connection lost: Route KDL-43W808C (com.google.android.gms/.cast.media.CastRemoteDisplayProviderService:bc8ffa28b17d8ad831d7421c50eb2ff4)
09-26 15:47:15.297  3595  3595 I MediaRouterService: Unselected route:Route KDL-43W808C (com.google.android.gms/.cast.media.CastRemoteDisplayProviderService:bc8ffa28b17d8ad831d7421c50eb2ff4)
09-26 15:47:15.312  3595  3595 V MediaRouter: Removing route: RouteInfo{ name=KDL-43W808C, description=BRAVIA 2015, status=DostÄpne, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO ROUTE_TYPE_REMOTE_DISPLAY , presentationDisplay=null }
09-26 15:47:15.314  3997  3997 V MediaRouter: Removing route: RouteInfo{ name=KDL-43W808C, description=BRAVIA 2015, status=ÅÄczÄ..., category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO ROUTE_TYPE_REMOTE_DISPLAY , presentationDisplay=null }
09-26 15:47:15.314  3997  3997 V MediaRouter: Selecting route: RouteInfo{ name=Telefon, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-26 15:47:15.358  4882  8450 I CastMirroringProvider: onDisconnect, display=RemoteDisplay{RemoteDisplayInfo{ id=bc8ffa28b17d8ad831d7421c50eb2ff4, name=KDL-43W808C, description=BRAVIA 2015, status=2, volume=0, volumeMax=0, volumeHandling=0, presentationDisplayId=-1 }}
09-26 15:47:15.361  3595  6171 I WifiService: releaseWifiLock uid=10076
09-26 15:47:15.365  4882  8467 D OpenGLRenderer: HWUI GL Pipeline
09-26 15:47:15.379  4882  8450 I CastSocketMultiplexer: Stopping multiplexer...
09-26 15:47:15.399  4882  8467 I Adreno  : QUALCOMM build                   : 8e59954, I0be83d0d26
09-26 15:47:15.399  4882  8467 I Adreno  : Build Date                       : 09/22/17
09-26 15:47:15.399  4882  8467 I Adreno  : OpenGL ES Shader Compiler Version: EV031.21.02.00
09-26 15:47:15.399  4882  8467 I Adreno  : Local Branch                     : O17A
09-26 15:47:15.399  4882  8467 I Adreno  : Remote Branch                    : 
09-26 15:47:15.399  4882  8467 I Adreno  : Remote Branch                    : 
09-26 15:47:15.399  4882  8467 I Adreno  : Reconstruct Branch               : `

**Comment by pdsouza** [comment]
Thanks for the detailed report.

Can you try [open_gapps-arm64-8.1-pico-20190831.zip](https://sourceforge.net/projects/opengapps/files/arm64/20190831/open_gapps-arm64-8.1-pico-20190831.zip/download)? That's what I have installed on my 5X with 0.6.7 and Chromecast is working fine.

**Comment by darekdeo** [comment]
Hi and thanks for fast response,

Using twrp I have wiped everything except internal storage and installed again maruos with gapps you have provided. Same issue, unfortunatelly.

**Comment by darekdeo** [comment]
Installed LineageOS 15.1, Cast works fine there.

Another thing to note is that during installation of Maru I couldn't add anything else to the installation queue - that's why after installing Maru I needed to reboot device to recovery again and install gapps separately. While installing LineageOS queue works fine and I am able to install both OS and gapps together.

**Comment by pdsouza** [comment]
OK, thanks for trying again and for your investigations.

Here is my testing procedure on my 5X:

0. Reboot to recovery (TWRP v3.2.3-0)
1. Install > select `maru-v0.6.7-update-bullhead-33301e64.zip`
2. Add more Zips > select `open_gapps-arm64-8.1-pico-20190926.zip`
3. Swipe to confirm Flash
4. Hit back until home screen > Wipe > Swipe to Factory Reset
5. Reboot System (I tapped do not install when prompted to install the TWRP app)
6. Go through the Google setup wizard to connect to WiFi and sign in to my Google account
7. Select Cast from Quick Settings dropdown and connect to my Chromecast (1st gen)
8. Verify that Maru Desktop automatically boots and is displayed on my Chromecast display

Noticing that my TWRP was outdated, I repeated the same procedure with TWRP v3.3.1-0 and had the exact same results. I did not run into the zip queue issue you mentioned with installing both Maru and gapps together. Which version of TWRP are you running?

If you could `shasum` your Maru package to make sure you don't have a corrupted file that would be good too, because this is very strange.

**Comment by darekdeo** [comment]
twrp is the same as yours: 3.3.1-0-bullhead
maru-v0.6.7-update-bullhead-33301e64.zip sha256 looks fine: 33301e64529f768ace748ed50de140750e65f2cdd9e79b6170fc5dcf47ddf046

I will try different versions of Maru: 0.6.5 and 0.6.6 (never tried these before) to confirm if it's just related to 0.6.7

**Comment by darekdeo** [comment]
My bad (I think), the installation process was incorrect on my side. While describing steps to reproduce here I did not noted that I was performing wipe before installing Maru (I mentioned it later after your first reply). So actually begining should be as follows:

- installed twrp and rebooted phone then runned recovery
- wiped previous system (everything except internal storage)
- installed maruos 0.6.7 from recovery and rebooted phone then back to recovery
- ...

The same way I've installed LineageOS 15.1 - wipe everything first, then install system. And it worked, both zip queue and Cast/Chromecast service.

Today I've followed your steps, first for Maru 0.6.6 and later for Maru 0.6.7, both worked fine this time. I was able to add gapps zip to queue and Cast/Chromecast is working. The only thing I did different today was that I haven't wiped previous system (LineageOS 15.1) before installing Maru. I've later did factory reset wipe as in the steps you have described.

I am not sure if this solved the issue as Lineage OS 15.1 was able to install successfully even if everything (except internal storage) was wiped before installing it.To me it looks like Maru needs some files from previous system installation to work correctly, but I am not as familiar with ROM flashing process.
