### ISSUE TITLE
Sprint SIMs crash when accessing Carrier Settings

### ISSUE THREAD

**Issue by pdsouza** [maruos/maruos#20]
I've had two reports so far that Sprint SIMs cause a crash when accessing `Settings > Wireless & Networks > Cellular networks > Carrier Settings`.

This is not reproducible on my carrier (AT&T).

Related post: https://groups.google.com/forum/#!topic/maru-os/0-jGC_FLD0Q

**Comment by bmallred** [comment]
Seeing the following from logcat

```
04-22 11:43:21.604   786  1248 I ActivityManager: START u0 {act=android.intent.action.MAIN cmp=com.lge.update/.SprintUpdateSetting} from uid 1001 on display 0
04-22 11:43:21.606   200   823 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
04-22 11:43:21.612  1233  1233 I chatty  : uid=1001(radio) expire 2 lines
04-22 11:43:21.616   200   823 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
04-22 11:43:21.616   200   823 D msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(15)
04-22 11:43:21.616   200   823 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
04-22 11:43:21.620   200   823 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
--------- beginning of crash
04-22 11:43:21.624  1233  1233 E AndroidRuntime: FATAL EXCEPTION: main
04-22 11:43:21.624  1233  1233 E AndroidRuntime: Process: com.android.phone, PID: 1233
04-22 11:43:21.624  1233  1233 E AndroidRuntime: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.lge.update/com.lge.update.SprintUpdateSetting}; have you declared this activity in your AndroidManifest.xml?
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1794)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3930)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:3890)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4213)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4181)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.preference.Preference.performClick(Preference.java:1012)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:3903)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-22 11:43:21.624  1233  1233 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-22 11:43:21.655   786  1489 W ActivityManager:   Force finishing activity com.android.phone/.MobileNetworkSettings
04-22 11:43:21.671  1883  1883 I chatty  : uid=1000(system) Binder_4 expire 4 lines
04-22 11:43:21.679   786 10840 I chatty  : uid=1000(system) RenderThread expire 2 lines
04-22 11:43:22.162   786   799 W ActivityManager: Activity pause timeout for ActivityRecord{a0701dd u0 com.android.phone/.MobileNetworkSettings t452 f}
04-22 11:43:22.991  1246  1246 I chatty  : uid=1000(system) Binder_5 expire 12 lines
04-22 11:43:22.994   200   823 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
04-22 11:43:23.029   786  1301 I WindowState: WIN DEATH: Window{82c134c u0 com.android.phone/com.android.phone.MobileNetworkSettings}
04-22 11:43:23.030   786   893 D ConnectivityService: unregisterNetworkFactory for Telephony
04-22 11:43:23.030   786   786 I MmsServiceBroker: MmsService unexpectedly disconnected
04-22 11:43:23.031   786   892 D WifiService: Client connection lost with reason: 4
04-22 11:43:23.032   192   192 I chatty  : uid=1000(system) /system/bin/servicemanager expire 7 lines
04-22 11:43:23.065   786  1248 I ActivityManager: Process com.android.phone (pid 1233) has died
04-22 11:43:23.065   786  1248 D ActivityManager: cleanUpApplicationRecord -- 1233
04-22 11:43:23.068   786  1248 W ActivityManager: Scheduling restart of crashed service com.android.mms.service/.MmsService in 1000ms
04-22 11:43:23.068   786  1248 W ActivityManager: Scheduling restart of crashed service com.android.phone/.TelephonyDebugService in 0ms
04-22 11:43:23.069   786  1248 W ActivityManager: Re-adding persistent process ProcessRecord{54f8557 1233:com.android.phone/1001}
04-22 11:43:23.079   786  1248 I ActivityManager: Start proc 10847:com.android.phone/1001 for restart com.android.phone
04-22 11:43:23.119 10847 10847 I chatty  : uid=1001(radio) expire 55 lines
04-22 11:43:23.176   786   804 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
04-22 11:43:23.339   936   936 W KeyguardUpdateMonitor: invalid subId in handleSimStateChange()
04-22 11:43:23.351 10847 10874 I chatty  : uid=1001(radio) expire 1 line
04-22 11:43:23.357   786   893 E ConnectivityService: Failed to find Messenger in unregisterNetworkFactory
04-22 11:43:23.358   786   893 D ConnectivityService: Got NetworkFactory Messenger for Telephony
04-22 11:43:23.441   786   786 I MmsServiceBroker: MmsService connected
04-22 11:43:23.508   786   892 D WifiService: New client listening to asynchronous messages
04-22 11:43:23.527   786   796 I Telecom : PhoneAccountRegistrar: New phone account registered: [[ ] PhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0} Capabilities: 54 Schemes: tel voicemail ]
04-22 11:43:23.534   786   796 I Telecom : : Sending phone-account intent as user
04-22 11:43:23.552   786   797 W Telecom : : No account found for the calling user
```

**Comment by pdsouza** [comment]
Thank you for the logs! Looks like we are missing some Sprint-specific activity in Carrier Settings...weird. I will need to investigate a factory image and see what Maru is missing.

**Comment by bmallred** [comment]
@pdsouza honestly let me know if you need more logs, testing, etc, and I'd be more than happy to provide them!

**Comment by pdsouza** [comment]
@bmallred Thank you, appreciate the help! I will get you a test build if I discover anything that could be a fix for you to verify.

**Comment by powderkegz** [comment]
I'm having the same issue on a Galaxy SIII, CR 5.1 d2spr 20170815 rom. Clicking "carrier" settings gives the error "com.android.phone has stopped".

Guess I'll reflash to stock to update PRL and Profile, but I hope this is fixable in a future build!

**Comment by pdsouza** [comment]
A potential fix has been included in hammerhead builds from [0.6.6](https://github.com/maruos/builds/releases/tag/v0.6.6) onwards. If someone can confirm this fixes the issue, that would be great. I use AT&T so I can't verify.
